### ISSUE TITLE
Can launchbox can be configured on linux

### ISSUE THREAD

**Issue by rebokdev** [retropassdev/RetroPass#1]
I have question:I'm linux user can i configure launchbox to work on retropass on linux

**Comment by retropassdev** [comment]
RetroPass only works on Xbox. Well technically, it works on Windows, but it's specifically designed for Xbox and gamepad.

LaunchBox is also Windows only, so if you want to setup your content metadata using LaunchBox, you would need to install a virtual machine on linux, using VirtualBox for example.

Another way would be to setup your content metadata with Emulation Station on linux, and then point that to RetroPass. It's a bit more complicated process, but it's doable.

**Comment by CoadyKidd** [comment]
Hi this app looks amazing but is there anyway you could make it just grab the photos from the RetroArch playlists in some way? Like as an option for ppl who want a easy to do look?

**Comment by Rose22** [comment]
> Hi, unfortunately RetroPass can't do that. It can only read LaunchBox or Emulation Station metadata. One of the reasons why it can't look into RetroArch metadata is that on Xbox each app is secure and sandboxed, so RetroPass can't access RetroArch local files.

what if you just let someone create a copy of the stuff retroarch scraped, and have retropass use that? so basically like, you make a copy of the retroarch metadata folder, put it in a place retropass can access, point retropass to it, and done. that seems like way less trouble than launchbox (which is windows only.....) and ES

**Comment by retropassdev** [comment]
Reading retroarch metadata might be possible if it's for example on a external drive, like when setting LaunchBox. That would require writing a new component that can read retroarch metadata. I'm very limited on my time at the moment, but will note this as a future enhancement.
