### ISSUE TITLE
Video Audio continues to play when exiting from game info

### ISSUE THREAD

**Issue by thundercato** [retropassdev/RetroPass#10]
Often when you click the 'A' button on a game to enter the game details screen then click 'B' quickly after the auto-play video's audio will continue to play in the background. If you go in to another (or the same) game details a new video will start playing with audio, but the original video's audio track also continues to play at the same time.

Unrelated Side note: Amazing work on this App team!! I can't believe it's not getting more coverage everywhere, it's a dream come true for me.

**Comment by retropassdev** [comment]
Thanks! It's a bit of a niche app, so not many people will find it useful, but we're very happy for those who do! :)
Thanks for the bug report, I'll look into it.

**Comment by retropassdev** [comment]
@thundercato Unfortunately, I can't reproduce this issue. Does this issue still happen on your system?

**Comment by thundercato** [comment]
My Xbox is at my holiday home so I haven’t used it recently. I will do a thorough check next time I’m there and update here. Cheers.
