### ISSUE TITLE
LaunchBox metadata not updating within RetroPass

### ISSUE THREAD

**Issue by b2dmx** [retropassdev/RetroPass#11]
I've added my games to launchbox, scraped the metadata, and corrected any errors I found and added sort names to keep things in proper order, such as Mortal Kombat, II, and 3 to be sorted as Mortal Kombat 1, 2, 3 respectively to keep them in proper order. However, all of my sort names are being ignored.

**Comment by retropassdev** [comment]
I tested this and can't reproduce the problem. Games are sorted by "Title" property, so if you change "Title" it should work. Also, Retropass should be restarted after any change in metadata.

**Comment by retropassdev** [comment]
I tested this and can't reproduce the problem. Games are sorted by "Title" property, so if you change "Title" it should work.
