### ISSUE TITLE
Selecting the correct RA core if using LaunchBox for metadata

### ISSUE THREAD

**Issue by swebbxbox** [retropassdev/RetroPass#12]
Loving the project. It is its own store, and that's great.

I had an issue that I was able to solve, and wanted to share in case anyone else ran into anything similar.

There is a file that determines which core you are going to load for a given system. (LaunchBox/Data/Emulators.xml) What works for PC may not work for Xbox. My personal issue was using desmume_libretro.dll instead of desmume2015_libretro.dll. The core is available in Xbox RA, but does not function.

I was able to edit the xml file using just notepad. I searched for "Nintendo DS", found the entry and made the change to the <CommandLine> parameter. I wasn't exactly sure of the filename, so I opened RA on my PC and downloaded that specific core, and the file name does match from PC to Xbox. That's usually a big assumption, but the libretro community generally likes things well formatted and tidy, so that helps.

I hope no one else runs into the issue, but if they do, I hope this helps. It may be worth adding to the install guide. Thanks again for the goods. It's a great app.

**Comment by retropassdev** [comment]
Thanks for reporting this. Yes, there might be some differences between cores on desktop and xbox. Your way of changing cores is  quick and easy.
