### ISSUE TITLE
Potential crash caused by ampersand (&) in ROM filename?

### ISSUE THREAD

**Issue by CWftw** [retropassdev/RetroPass#13]
I'm not sure how to confim this, but I noticed various specific games crashing reliably on launch (ToeJam & Earl, ToeJam & Earl in Panic on Funkotron, Dungeons & Dragons - Warriors of the Eternal Sun, Battletoads & Double Dragon). After investigating such things as bugs relating to loading ZIP files in the Genesis Plus GX Libretro fork (they are all ZIPs) and confirming they do load through RetroArch itself I began to see the "&" pattern and tested a few more games to confirm my suspicion. Am I crazy, or is this a bug?

**Comment by retropassdev** [comment]
Thanks. Can you give me more info on this?
1. Does RetroPass itself crash and you need to restart it?
2. If RetroPass doesn't crash, is RetroArch properly started? Can you see a splash screen? Or is it immediately shut down and you're back to home screen?
3. Do you experience this issue only with Genesis Plus GX core?
Thanks!

**Comment by CWftw** [comment]
- RetroPass is still open in the background
- I see RetroArch splash screen then it crashes
- None of my ROMs for any other platforms have &'s, I did try changing Genesis to Picodrive in Launchbox. Most games work fine, the problem ones still crash.

**Comment by mattbarton85** [comment]
Any rom with "&" or "+" in the title when selected shows the retro arch splash then crashes and instantly sends you back to Xbox home screen
