### ISSUE TITLE
Retropass Menu Collor looks off

### ISSUE THREAD

**Issue by Thora-G** [retropassdev/RetroPass#14]
Hi i have a small Strange problem ,it looks like some colors are missing or colors are inverted on my Xbox in Retropass, everything else works fine.
Here are a few pictures where you can see the problem

https://abload.de/img/mukc4.jpg

https://abload.de/img/2hjh1.jpg

Edit: after Watching some youtube clips i figured out the problem , my Xbox design (Color for background and other stuff) messed with retropass . After going back to the default color everything is fine.

**Comment by thundercato** [comment]
This is an issue that I also have occasionally. I find if I reset my xbox it goes back to the correct colours.

**Comment by Thora-G** [comment]
Tried that already but no success but i never hat the right colors, they were always messed up

**Comment by retropassdev** [comment]
Yes, for text, retropass is using standard defined font styles, so the color will depend on the current theme. How does Game Pass look under your theme? Does it keep its own colors regardless? I could simply lock the original colors and ignore the theme.

**Comment by Thora-G** [comment]
Most of Game Pass looks the same the only difference is the border around the selected game(color of your theme ,design), that is the only thing that changes with Game pass.

**Comment by retropassdev** [comment]
@Thora-G @thundercato Can you give me details of your settings, like what are your customized settings. I checked, and when setting theme to Light, Game Pass uses light (white) background colors with dark text. Retropass changes text, but it has hardcoded background values so it doesn't adjust well to Light theme on xbox. This will be fixed, but If you can share some of your theme/color settings, that would be great, so I can properly test.

**Comment by thundercato** [comment]
My Xbox is at my holiday home. So will get that info and pass it on next time I’m there.

**Comment by Thora-G** [comment]
At the moment i only have the dark theme and the color is Orange .
