### ISSUE TITLE
fds games wont launch on xbox series x

### ISSUE THREAD

**Issue by manwichman44** [retropassdev/RetroPass#15]
I've done everything I know how to do. I've checked and rechecked to make sure the bios file is correct, I've messed with naming, moved files to and from the Xbox and external drive. Nothing I do works. When I choose an fds game, it'll boot retroarch for a second and then crashes. I've even tried different cores in launchbox setup. When I run the game in retroarch itself, it runs fine. I've checked the retroarch log and I noticed that it always says it fails to load content. i also get a "not an iNES file" error. Again, I don't know what else to do. Do you have any suggestions? Blow is what the log says.

[INFO] === Build =======================================
[INFO] CPU Model Name: Unknown
[INFO] Capabilities:  MMX MMXEXT SSE SSE2 SSE3 SSSE3 SSE4 SSE4.2 AES AVX AVX2
[INFO] Built: Apr 30 2022
[INFO] Version: 1.10.3
[INFO] =================================================
[INFO] [Input]: Found input driver: "uwp".
[INFO] [Core]: Loading dynamic libretro core from: "cores\fceumm_libretro.dll"
[INFO] [Overrides]: No core-specific overrides found at "Q:\Users\UserMgr0\AppData\Local\Packages\50209Gamr13.x.RetroArch.X1_zyhg31h2xwk3g\LocalState\config\FCEUmm\FCEUmm.cfg".
[INFO] [Overrides]: No content-dir-specific overrides found at "Q:\Users\UserMgr0\AppData\Local\Packages\50209Gamr13.x.RetroArch.X1_zyhg31h2xwk3g\LocalState\config\FCEUmm\\videos.cfg".
[INFO] [Overrides]: No game-specific overrides found at "Q:\Users\UserMgr0\AppData\Local\Packages\50209Gamr13.x.RetroArch.X1_zyhg31h2xwk3g\LocalState\config\FCEUmm\Nazo no Murasame Jou.cfg".
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Environ]: GET_VFS_INTERFACE. Core requested version >= V1, providing V3.
[INFO] [Environ]: RETRO_ENVIRONMENT_SET_CONTENT_INFO_OVERRIDE.
[INFO] [Content Override]: File Extension: 'fds' - need_fullpath: FALSE, persistent_data: FALSE
[INFO] [Content Override]: File Extension: 'nes' - need_fullpath: FALSE, persistent_data: FALSE
[INFO] [Content Override]: File Extension: 'unf' - need_fullpath: FALSE, persistent_data: FALSE
[INFO] [Content Override]: File Extension: 'unif' - need_fullpath: FALSE, persistent_data: FALSE
[INFO] [Remaps]: Remap directory: "Q:\Users\UserMgr0\AppData\Local\Packages\50209Gamr13.x.RetroArch.X1_zyhg31h2xwk3g\LocalState\config\remaps\".
[INFO] [Overrides]: Redirecting save file to "D:\Saves\Nazo no Murasame Jou.srm".
[INFO] [Overrides]: Redirecting save state to "D:\States\Nazo no Murasame Jou.state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: SET_SUPPORT_ACHIEVEMENTS: yes.
[INFO] [Environ]: GET_MESSAGE_INTERFACE_VERSION.
[INFO] [Environ]: GET_LANGUAGE: "0".
[INFO] [Content]: Content loading skipped. Implementation will load it on its own.
[INFO] [Environ]: RETRO_ENVIRONMENT_GET_GAME_INFO_EXT.
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[libretro INFO] Frontend supports RGB565 - will use that instead of XRGB1555.
[INFO] [Environ]: PERFORMANCE_LEVEL: 5.
[INFO] [Environ]: SYSTEM_DIRECTORY: "D:\bios".
[libretro WARN] Not an iNES file!
[libretro INFO]  FCEU_MakeFName: D:\bios\disksys.rom
[libretro WARN] An error occurred while loading the file.
[ERROR] [Content]: Failed to load content
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading core..
[INFO] [Core]: Unloading core symbols..
[ERROR] Init failed
[WARN] Initialization failed, so not running
[INFO] [Config]: Saved new config to "Q:\Users\UserMgr0\AppData\Local\Packages\50209Gamr13.x.RetroArch.X1_zyhg31h2xwk3g\LocalState\retroarch.cfg".

**Comment by manwichman44** [comment]
So, I looked a little further into it and even though the bios was there, it couldn't find it for some reason, I redid my launchbox setup to see if I could fix it since retropass uses the launchbox metadata, and that seemed to fix it. Thank you for your awesome app!

**Comment by retropassdev** [comment]
Awesome! Thank you for reporting back for anyone else who will have a similar issue. A general rule is that if it works from Launchbox,, it should work from RetroPass. If it works from Launchbox but not from Retropass, then it might be a potential issue In this case, it looks like it was just the launch setup.

Thanks!
