### ISSUE TITLE
Starting a game launches RetroArch, and then nothing happens.

### ISSUE THREAD

**Issue by snshane** [retropassdev/RetroPass#16]
As the title says, nothing is happening.

It's just sitting at the home screen. No error message, just nothing.

This occurs with any console.  I have rebooted the Xbox, but the issue remains.

**Comment by retropassdev** [comment]
Have you installed LaunchBox directly to your external drive? This usually hapens when LaunchBox is installed and set up on internal drive and then copied to external.

**Comment by retropassdev** [comment]
I would need more data to identify the problem. Make sure to exactly follow installation guide or video tutorials. Closing it for now.
