### ISSUE TITLE
retropass went blank

### ISSUE THREAD

**Issue by nananana11** [retropassdev/RetroPass#18]
I deleted several roms for not working not realizing it was the "&" in the name causing it, anyway I got the update which definitely fixed it so I added the roms back in, went through the motions with launchbox yada yada yada. Put the external ssd back in my xbox suddenly an entire system has no art, go back to launchbox everything looks good on there so I hard restarted my xbox, tried again, now its completely blank, nothing shows up at all. I'm on retail by the way.

I should note that the very first time I installed it and set up retropass it did this exact thing, completely blank. I messed around with the launchbox emulator xmls(deleted alternate names and controller settings of each platform) and poof it worked, tried that again still blank. Unfortunately, only did it not fix retropass but it ended up corrupting my entire launchbox install and that was really something, had to pull teeth to uninstall it because it'd instant crash. I'm not sure why doing the first time was okay but not the second and why it had to be such a pain to remove. As a hail mary I reinstalled launchbox and moved my backed up boxart images back in and nothing, still blank. Tried deleting systems, nope, removed all the images leaving blank metadata, nada, nothing seems to work. Oh and I enabled logging, the log file is perpetually empty so there's that.

I have no clue why adding in a handful of games that were already there before just a few weeks ago messed everything up but it do. I'm mentally drained from testing it so many times (and from dealing with launcbox) so I'm resigned to using the emulators directly at this point. In any case I figured I'd let you know, I don't know how helpful this post will be but there you go. I enjoyed it a lot while it worked so thanks for that, it was nice while it lasted. Hopefully you'll be able to glean something useful from what happened, if not then oh well, I'm sure it was just bad luck on my end. Cheers.

**Comment by retropassdev** [comment]
Hi! 
Sorry to hear you're having problems and especially that your launchbox config is corrupt. I know these things take time to set up. It is difficult for me to tell what is the exact problem without actually trying the configuration, but here are a few thoughts:

- When you mention "completely blank", does it just show the main page without any platforms, empty?
- Did you try going to settings, and if so, does it show the message it is missing Retropass.xml file?
- Did you install launchbox directly to your external drive? Or if you have multiple launchbox installations, did you use the one from the external drive to modify your data?
- Manually modifying xml might be a bit risky and could lead to launchbox metadata corruption.
- For logging to work, Retropass must be closed/quit, not just suspended, so maybe that's why there was no logging?

For more help or if you wish to share your config, you can find me on Discord here https://discord.gg/bFG8pAKe

Thanks.

**Comment by nananana11** [comment]
Thanks for the quick reply, I forgot to mention something. I was messing around with the retropass.xml, deleting it and adding it back etc, I deleted it and opened retropass again nothing changes, takes a bit for it to realize it's gone and only when it's been closed for some time or I restart the xbox.. Same thing happens with removing the external ssd entirely, takes some time for it to catch up and only after closing/opening it multiple times. It's like it detects the xml but nothing else, as if there's no launchbox, makes me think it's related to the external ssd itself. I have considered formatting it but that's a commitment I'm not ready to make at this time, too many other things on the drive I'd have to back up, old shows and the like. Oh and when I put the games back on right before this happened, windows put a system volume folder on the drive, never did that before, I don't know if that affects anything, was still able to do everything else the same as before, read/write etc, I know because I deleted some MAME roms that wouldn't run on retroarch right off the xbox (had them removed from the retropass list before this so I didn't see them.) 

Also completely forgot to mention this, an entire system was missing as well when this first started, at the bottom SNES suddenly had no art and MAME, which was usually below it was just gone entirely, both looked normal on launchbox and only the former had a game reinstated after the retropass update. There was actually a second time I edited the launchbox xml, right at the beginning when I added a new system after confirming retropass was working (I only added one system originally to get it up and running) a handful of games wouldn't launch and I deleted the same things as the other to make it work. I did find it odd that every system I added thereafter didn't need it's respective xml modified but didn't give it much thought, the system that initially lost it's art and the one that disappeared never had their xml files modified. 

As for your questions, yeah, it's "working" settings, search, all that is there but no systems below the search, nothing comes up when search is used. Settings shows the usual, nothing out of the ordinary, delete cache- which doesn't do anything when it's like this. I did install launchbox to the external but when I reinstalled it acted like there was one already installed on my pc which there wasn't, I definitely didn't put it on the PC drive yet it said there was an instance already running when I went to reinstall despite not having it installed on my pc and it having been uninstalled from my external ssd. As for the corruption yeah I'm learning that now lol, not like it matters, clearly that ship already sailed before the corruption happened, I tried removing those games with the "&" I added back in first before messing with the xml which did nothing. I didn't test completely rescraping again and I'm not going to, even with the names being correct it somehow manages to miss almost everything so it's extremely time consuming. 

Funny thing about the logging I just remembered, I can't remember now but the first time I ran retropass when it was blank it did log something and whatever it showed in the log was what got me to edit the launchbox xml in the first place which fixed the problem. This time though nothing, I turned it on right after I restarted the xbox when it first went blank and the log has been empty ever since.

I'm assuming something messed up in launchbox and corrupted the external ssd, those are the only things that had any changes before this began, the fact that launchbox was so difficult to remove when this happened makes me think it corrupted my ssd which could be the cause. Perhaps someday when I'm feeling masochistic I'll back up everything and reformat my drive and try the other front end setup, I don't ever want to use launchbox again, the terrible scraping forcing manual boxart allocation for most games was form of torture lol. Using retropass is one of those things where I don't want to go back, I'm gonna have that nice interface burned into the back of my mind as I'm scrolling pages of plain text to launch games so I'll probably to give it another try eventually, fatigue is the only thing stopping me right now lol.

Thanks for the quick response and the discord link, once I accepted things were FUBAR after reinstalling launchbox I ended up wiping everything except for my backed up boxart since I no longer trust having it on the drive so there's no config anymore. I could reinstall launchbox one last time and scan the games without copying the boxart to the folders and see if that works and share the config if it doesn't work but honestly I would rather burn my eyes out with a red hot poker than ever touch launchbox again. I have a frontend on my android shield tv and that's what I'm used to when it comes to frontends and I didn't realize just how exceptionally good it is until I used launchbox, it really spoiled me with it's ease of use. Launchbox definitely corrupted my drive even if it's still completely functional, I had to jump through hoops to remove it the first time, couldn't delete anything from its directory from windows file browser at all.

At this point I'm fairly positive launchbox was corrupt before I edited the xml even if it didn't have any blatantly obvious signs of it beyond things going missing and the retropass log being empty. It wasn't exactly on stable ground to begin with, with it constantly needing to be tinkered with to make games display and run properly from the start. Every system I added was trial and error getting things to work, it would look fine on launchbox then when I the drive in the xbox art would just not be there, games wouldn't launch that otherwise would if launched from retroarch directly (no "&" in the name either) so it completely breaking wasn't that much of a surprise it's just strange that it's stuck like that now with no logging and no feedback at all. If I try it again down the road with the other front end I'll let you know how it goes, good or bad. Thanks again for your help. Cheers.

**Comment by retropassdev** [comment]
Thank you for a thorough description of the whole issue. Yeah, I can imagine you had enough, so a break from all the setting and configuring sounds good :)
Launchbox is fairly straightforward when doing clean install and config, but yeah, I really don't know if there are any problems when updating stuff. Another thing I remembered about the "&", if you accidentally added those directly into your launchbox xml files with a list of games, then this would make xml invalid as you need to use &amp; instead. But if you did it through Launhbox then this should not be a problem.

In any case, thank you very much for investing your time into trying it, testing and sending a report.

**Comment by retropassdev** [comment]
Thank you for a thorough description of the whole issue. Yeah, I can imagine you had enough, so a break from all the setting and configuring sounds good :)
Launchbox is fairly straightforward when doing clean install and config, but yeah, I really don't know if there are any problems when updating stuff. Another thing I remembered about the "&", if you accidentally added those directly into your launchbox xml files with a list of games, then this would make xml invalid as you need to use &amp; instead. But if you did it through Launhbox then this should not be a problem.

In any case, thank you very much for investing your time into trying it, testing and sending a report.

**Comment by nananana11** [comment]
I don't know how helpful it was, but thanks for humoring me regardless lol. I don't think the other front end could be any worse, I can take the tedium so long as I'm getting some feedback that what doing is or isn't working and get a rhythm going, with launchbox it was like every time I thought I had everything just right something would break with no indication why. That first time running retropass the launchbox platform xml had something in it that broke the ability for retropass to access the game and art, I can't remember what it was now but if not for the log I would've been at a complete loss but at least I could understand the logic of why it wasn't working in that specific instance. But with so many other things after that it was seemingly random, no rhyme or reason to it, there was no indication anything was wrong from launchbox. So long as there's some logic I can follow with emulationstation I can get into a rhythm setting it up and knock it out, launchbox constantly broke that rhythm and was just tedious with all the unnecessary steps it took to fix things that, on the surface, looked fine until it was plugged into the xbox.

Thanks for the heads up though and, again, for letting me ramble about all my testing. Hopefully I'll something good to report down the road, the retropass app so much better than looking at and scrolling through text it's gonna drive me nuts lol, it's only a matter of time before I bite the bullet and try again. I'll keep you posted, take care.

**Comment by retropassdev** [comment]
Closing for now.
