### ISSUE TITLE
[Feature Request] Add support for XBSX2

### ISSUE THREAD

**Issue by danprice142** [retropassdev/RetroPass#19]
It would be good if RetroPass could launch XBSX2 and Flycast UWPs. Currently the pcsx2 core is way behind XBSX2 and does not support online play and the Flycast core does not support online play either so adding support for both of these UWPs could allow us to launch Better quality PS2 games and online games from both apps

**Comment by retropassdev** [comment]
Hi, thanks for the suggestion.

XBSX2 support is currently in development. It already works but needs polish and testing.
For Flycast, I'm not sure how involved it would be to add stuff to their side, but will consider it.
