### ISSUE TITLE
Some Games don't show box art

### ISSUE THREAD

**Issue by CoadyKidd** [retropassdev/RetroPass#2]
these are games with unofficial box art such as Sonic & Knuckles + Sonic 3 and Angry Birds for the psp i think to fix this you would have to make it so if theres no Box Art it goes to the Fan Art - Box Art folder instead

**Comment by CoadyKidd** [comment]
if you copy and paste manually it fixes it

**Comment by retropassdev** [comment]
LaunchBox has /Data/Platforms.xml where all the image and video folders are defined. For each MediaType there is a FolderPath. These media types are supported while others are ignored:
"Screenshot - Game Title"
"Screenshot - Gameplay"
"Screenshot - Game Select"
"Video"

"Screenshot - Game Title" is searched for box art, so it's best to put the images there. I will update documentation with more details about asset loading and what's supported.
