### ISSUE TITLE
[Feature Request] Retropass support for multiple HDDs

### ISSUE THREAD

**Issue by Wuzzy1988** [retropassdev/RetroPass#21]
I have two drives that work independently of each other. One for PS2 games and the other for everything else. With both drives plugged in, Retroarch will always prioritise the D drive, with no way to switch to the E drive or show both drives combined.

Could you look into a solution for those with multiple drives? 

<img width="430" alt="discord screencap" src="https://user-images.githubusercontent.com/16304791/194783273-4e1cece1-c012-43a6-b558-5ef339bc118c.png">

**Comment by retropassdev** [comment]
A quick update. This feature is implemented and in testing phase.
