### ISSUE TITLE
How to setup with XBSX2 and Dolphin Standalone

### ISSUE THREAD

**Issue by deliyuerek85** [retropassdev/RetroPass#24]
Hi,

as there is now support for xbsx2 and dolphin standalone, I am wondering how to setup retro pass with these emulators. I can't find any tutorial anywhere.

**Comment by dxcotoxb** [comment]
You must instal the emulators in windows (extract). In launchbox. Add emulator. Search the .exe of them. 
After do this. Select pcsx2 and dolphin as default emulator for each plataform. 

https://youtu.be/gn_CS6NfbNY


Sorry by my bad english.

**Comment by retropassdev** [comment]
Documentation for setting up retropass with xbsx2, dolphin and xenia canary is updated.
