### ISSUE TITLE
[Feature Request] Playlist sorting order

### ISSUE THREAD

**Issue by MistaJulius** [retropassdev/RetroPass#25]
Can the sorting order be changed so playlists load first at the top of list above platforms, rather than last at bottom. I know its been mentioned already on discord, be good if this happened.

**Comment by retropassdev** [comment]
Noted. This option doesn't exists but it will be added at some point.

**Comment by retropassdev** [comment]
Support will be added for defining custom placement of playlists and platforms. This will be configured in LaunchBox through "Sort Title" property. Should be added to v1.4.0.

**Comment by retropassdev** [comment]
Quick update, the feature is implemented and currently in performance optimization and testing phase.
