### ISSUE TITLE
Feature Request - Game Sort Title

### ISSUE THREAD

**Issue by kesslerboy81** [retropassdev/RetroPass#33]
Hey gang

Keep up the excellent work. This has really made Emulation on the Xbox more tolerable and user friendly. I have one request at this stage. Considering you've implemented Platform/Playlist Sort Titles, would it be possible to include Game Sort Titles per platform? 

It's a small request but will certainly make the collections look more presentable.

Thank you

**Comment by retropassdev** [comment]
Hi, thanks very much! Always a pleasure to see people getting value from retropass.
Regarding Game sorting per platform, is this something that can be done in LaunchBox? I tried to arrange it by going to Arrange By option in the menu, but this applies sorting to all platforms. I quickly checked metadata for platforms and can't find any property that would save this choice, so I'm thinking this is applied at the app level.

**Comment by kesslerboy81** [comment]
Hi there,You can do it in Launchbox, but once the games load up in Retropass they’re in alphabetical order.So the Sort Order from Launchbox to Retropass doesn’t seem to be translating.On 14 Apr 2023, at 15:34, retropassdev ***@***.***> wrote:﻿
Hi, thanks very much! Always a pleasure to see people getting value from retropass.
Regarding Game sorting per platform, is this something that can be done in LaunchBox? I tried to arrange it by going to Arrange By option in the menu, but this applies sorting to all platforms. I quickly checked metadata for platforms and can't find any property that would save this choice, so I'm thinking this is applied at the app level.

**Comment by retropassdev** [comment]
That's true. Right now there is just basic alphabetical sorting for games inside platforms. Can you give me a quick info how to do sorting per platform in LB? thanks!

**Comment by kesslerboy81** [comment]
An example, for Secret of the Monkey Island in ScummVm or MS Dos, I would go to Monkey Island 2 in Launchbox and rename Sort title as Secret of Monkey Island 2. And then for The Curse of Monkey Island, Secret of Monkey Island 3 etc. so then when you see them on the platform, they’re all there in the correct order.The Street Fighter series is another example. In dirt title I’ll just rename them Street Fighter (and whatever correct order number) for each game. On 14 Apr 2023, at 15:41, retropassdev ***@***.***> wrote:﻿
That's true. Right now there is just basic alphabetical sorting for games inside platforms. Can you give me a quick info how to do sorting per platform in LB? thanks!

**Comment by retropassdev** [comment]
Oh, I understand. You'd like manual sorting with Game SortTitle. Ok cool, I'll look into that. Should be possible. Thanks for clarifying.

**Comment by kesslerboy81** [comment]
Thank you. Again, keep up the great work. It’s appreciated.On 14 Apr 2023, at 15:48, retropassdev ***@***.***> wrote:﻿
Oh, I understand. You'd like manual sorting with Game SortTitle. Ok cool, I'll look into that. Should be possible. Thanks for clarifying.
