### ISSUE TITLE
[feature request] Switch to next/previous game preview window using the analog triggers

### ISSUE THREAD

**Issue by Masselboy** [retropassdev/RetroPass#40]
Once in the game info window, switch to the window of the previous or next game using the left and right trigger to scroll through the game library without going back to the library screen first.

**Comment by retropassdev** [comment]
Sounds like a good feature. I'll try to implement it for the next release. Thanks.

**Comment by Masselboy** [comment]
Oh cool, thanks for seriously considering it. :) I forgot something else, a mute setting for the autoplay videos would be useful as well. Hope you don‘t feel spammed by my requests. All the best!
Am 1. Okt. 2023, 21:33 +0200 schrieb retropassdev ***@***.***>:

**Comment by retropassdev** [comment]
A mute setting for the video....never thought of it, but it does seem useful. Yeah, no worries, it's good to get some feedback and things that could be improved.
